baseURL = "https://blog.raphaelbarbazza.com/"
languageCode = "en-us"
title = "rbarbazz"
theme = "minimal-bootstrap-hugo-theme"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[params]
showPostSummary = true

[menu]
  [[menu.nav]]
  name = "Posts"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "Tags"
  url = "/tags/"
  weight = 2
