baseURL = "https://blog.raphaelbarbazza.com/"
languageCode = "en-us"
title = "rbarbazz's blog"
theme = "harbor"
paginate = 3

[outputs]
  section = ["HTML"]

[[params.nav]]
  identifier = "home"
  name = "Home"
  icon = "fas fa-home fa-lg"
  url = ""
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3

[[params.social]]
  name="Github"
  url="https://github.com/rbarbazz"
  icon = "fab fa-github fa-lg"
